Repository maks-sh/scikit-uplift, pull requests merged in 2021-02, with the labels that each got.

#76 🧁 Fix metrics: make string percentiles
  sklift/metrics/metrics.py
  sklift/viz/base.py
Labels: enhancement

#81 Test datasets
  sklift/datasets/datasets.py
  sklift/tests/test_datasets.py
Labels: bug

#82 🥳 Uplift metrics tutorial notebook
  notebooks/uplift_metrics_tutorial.ipynb
Labels: documentation, enhancement

#83 Fix docs
  Readme.rst
  docs/changelog.md
  docs/tutorials.rst
  notebooks/Readme.rst
  notebooks/pipeline_usage_RU.ipynb
  notebooks/uplift_metrics_tutorial.ipynb
Labels: documentation
